version: '3.8'

services:
  wishlist:
    image: wishlist:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: /root/wishlist/.env  # Env variables on the server
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
