name: Deploy to Hetzner

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx for multi-platform support (optional, if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub or GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 4: Build and push Docker image to GitHub Container Registry (or Docker Hub)
    - name: Build and push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:latest

    # Step 5: SSH into Hetzner server and pull the latest image, then deploy it
    - name: Deploy to Hetzner
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HETZNER_IP }}
        username: ${{ secrets.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        port: 22
        script: |
          # Pull the latest image
          docker pull ghcr.io/${{ github.repository }}:latest
          
          # Stop and remove the existing container (if running)
          docker-compose -f /root/wishlist/docker-compose.yml down || true

          # Start the container with the updated image
          docker-compose -f /root/wishlist/docker-compose.yml up -d --force-recreate
